language: cpp
compiler:
  - gcc
  - clang
# trusty (14.04) is now used instead of precise (12.04)
sudo: required
dist: xenial
before_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..
script: make && make test

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libboost1.55-all-dev
